version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Decode keystore
          command: echo $ENCODED_KEYSTORE | base64 --decode >> $KEYSTORE_NAME
      - run:
          name: Decode keystore.properties
          command: echo $ENCODED_KEYSTORE_PROPERTIES | base64 --decode >> keystore.properties
      - run:
          name: Update keystore path
          command: sed -i 's|home/.*|$KEYSTORE_PATH|' keystore.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results